### ISSUE TITLE
A Spanish version of this page is available

### ISSUE THREAD

**Issue by vicentequintero** [danila-shirkov/exercises-javascript#10]
https://github.com/danila-shirkov/exercises-javascript/blob/62ebc0f5a15fd4cb954c762d902331c9ebdc8de0/exercises-javascript_all_link.txt#L458C1-L458C1

https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Statements/while)

**Comment by yana-fesenko** [comment]
@vicentequintero ссылка что ты предлагаешь открывается на русском языке, надо переделать

**Comment by vicentequintero** [comment]
https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Statements/while

**Comment by yana-fesenko** [comment]
@vicentequintero ok, bien. Por favor cierra el issue cuando ya cambias el enlace
