### ISSUE TITLE
Reemplazar por versión en ES

### ISSUE THREAD

**Issue by vicentequintero** [danila-shirkov/exercises-javascript#11]
https://github.com/danila-shirkov/exercises-javascript/blob/62ebc0f5a15fd4cb954c762d902331c9ebdc8de0/exercises-javascript_all_link.txt#L346C1-L346C1

https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Global_Objects/String/toUpperCase

**Comment by yana-fesenko** [comment]
@vicentequintero отлично ок

**Comment by yana-fesenko** [comment]
@vicentequintero Por favor cierra el issue cuando ya cambias el enlace
