### ISSUE TITLE
Page does not exist

### ISSUE THREAD

**Issue by vicentequintero** [danila-shirkov/exercises-javascript#15]
https://github.com/danila-shirkov/exercises-javascript/blob/62ebc0f5a15fd4cb954c762d902331c9ebdc8de0/exercises-javascript_all_link.txt#L197C3-L197C3

https://learn.microsoft.com/es-es/dotnet/visual-basic/programming-guide/language-features/constants-enums/constant-and-literal-data-types

**Comment by yana-fesenko** [comment]
@vicentequintero эту ссылку обсудили в питоне. нужно про literal (informatica). en python está en inglés, la puedes poner eng

**Comment by vicentequintero** [comment]
https://en.wikipedia.org/wiki/Literal_(computer_programming)

**Comment by yana-fesenko** [comment]
@vicentequintero ok, dejamos esta. Por favor cierra el issue cuando ya cambias el enlace
