### ISSUE TITLE
page does not exist

### ISSUE THREAD

**Issue by vicentequintero** [danila-shirkov/exercises-javascript#16]
https://github.com/danila-shirkov/exercises-javascript/blob/62ebc0f5a15fd4cb954c762d902331c9ebdc8de0/exercises-javascript_all_link.txt#L212

Replace for https://es.wikipedia.org/wiki/Tipado_fuerte

**Comment by yana-fesenko** [comment]
@vicentequintero https://ru.wikipedia.org/wiki/Сильная_и_слабая_типизация - это оригинал надо найти похожую по смыслу. смысл про сильную и слабую типизацию

**Comment by vicentequintero** [comment]
https://en.wikipedia.org/wiki/Strong_and_weak_typing

На английском

**Comment by yana-fesenko** [comment]
@vicentequintero ok, dejemos esta https://en.wikipedia.org/wiki/Strong_and_weak_typing
Por favor cierra el issue cuando ya cambias el enlace
