### ISSUE TITLE
Page does not exist

### ISSUE THREAD

**Issue by vicentequintero** [danila-shirkov/exercises-javascript#17]
https://github.com/danila-shirkov/exercises-javascript/blob/62ebc0f5a15fd4cb954c762d902331c9ebdc8de0/exercises-javascript_all_link.txt#L331C11-L331C76

https://es.wikipedia.org/wiki/Par%C3%A1metro

**Comment by yana-fesenko** [comment]
@vicentequintero посмотри пожалуйста страницу, как в оригинале  https://ru.wikipedia.org/wiki/Параметр_(программирование. надо найти похожую по смыслу на исп, если нет на исп, значит на англ

**Comment by vicentequintero** [comment]
El artículo equivalente sería: https://es.m.wikipedia.org/wiki/Argumento_(informática)

Según la propia base de datos de wikipedia al comparar versiones.

**Comment by yana-fesenko** [comment]
@vicentequintero ok, está bien. Por favor cierra el issue cuando ya cambias el enlace
