### ISSUE TITLE
Wiki ES

### ISSUE THREAD

**Issue by vicentequintero** [danila-shirkov/exercises-javascript#21]
https://github.com/danila-shirkov/exercises-javascript/blob/5873ac8ad87b7a51b730bda085de07e102d1fcee/exercises-javascript_all_link.txt#L43

https://es.wikipedia.org/wiki/Resto

**Comment by vicentequintero** [comment]
https://es.wikipedia.org/wiki/División_euclídea

**Comment by yana-fesenko** [comment]
@vicentequintero [https://es.wikipedia.org/wiki/División_euclídea](https://es.wikipedia.org/wiki/Divisi%C3%B3n_eucl%C3%ADdea) está bien. Por favor cierra el issue cuando ya cambias el enlace
